### ISSUE TITLE
Cannot find 'DropConnect' in 'myclass'

### ISSUE THREAD

**Issue by baojunshan** [WHUIR/PPVAE#5]
Cannot find 'DropConnect' in 'myclass'

**Comment by kduxin** [comment]
Simply remove it from "pretrainVAE.py" should work. 
I found it also necessary to remove "MH_GRU".

**Comment by baojunshan** [comment]
> Simply remove it from "pretrainVAE.py" should work.
> I found it also necessary to remove "MH_GRU".

thanks a lot!
